	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 00
	tilecoll WALL, WALL, FLOOR, FLOOR ; 01
	tilecoll WALL, WALL, WALL, WALL ; 02
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 03
	tilecoll FLOOR, LADDER, FLOOR, FLOOR ; 04
	tilecoll FLOOR, LADDER, FLOOR, FLOOR ; 05
	tilecoll WALL, WALL, BOOKSHELF, BOOKSHELF ; 06
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 07
	tilecoll WALL, WALL, FLOOR, FLOOR ; 08
	tilecoll WALL, WALL, WALL, FLOOR ; 09
	tilecoll WALL, WALL, FLOOR, WALL ; 0a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0b
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 0c
	tilecoll WALL, FLOOR, WALL, FLOOR ; 0d
	tilecoll FLOOR, WALL, FLOOR, WALL ; 0e
	tilecoll WALL, WALL, WALL, WALL ; 0f
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 10
	tilecoll FLOOR, FLOOR, WALL, WALL ; 11
	tilecoll WALL, WALL, WALL, WALL ; 12
	tilecoll WALL, WALL, WALL, WALL ; 13
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 14
	tilecoll WALL, WALL, FLOOR, FLOOR ; 15
	tilecoll WALL, WALL, WALL, WALL ; 16
	tilecoll WALL, WALL, WALL, WALL ; 17
	tilecoll WALL, WALL, FLOOR, FLOOR ; 18
	tilecoll WALL, WALL, WALL, WALL ; 19
	tilecoll WALL, WALL, WALL, FLOOR ; 1a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1b
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1c
	tilecoll WALL, STAIRCASE, FLOOR, FLOOR ; 1d
	tilecoll WALL, WALL, FLOOR, COUNTER ; 1e
	tilecoll WALL, WALL, FLOOR, FLOOR ; 1f
	tilecoll FLOOR, FLOOR, WALL, WALL ; 20
	tilecoll WALL, WALL, WALL, FLOOR ; 21
	tilecoll WALL, FLOOR, WALL, FLOOR ; 22
	tilecoll WALL, FLOOR, WALL, WALL ; 23
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 24
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 25
	tilecoll FLOOR, FLOOR, WALL, WALL ; 26
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 27
	tilecoll WALL, WALL, FLOOR, FLOOR ; 28
	tilecoll WALL, WALL, FLOOR, FLOOR ; 29
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 2a
	tilecoll WALL, FLOOR, WALL, FLOOR ; 2b
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 2c
	tilecoll WALL, WALL, FLOOR, FLOOR ; 2d
	tilecoll WALL, FLOOR, WALL, FLOOR ; 2e
	tilecoll WALL, FLOOR, WALL, FLOOR ; 2f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 30
	tilecoll COUNTER, COUNTER, FLOOR, FLOOR ; 31
	tilecoll WALL, WALL, FLOOR, FLOOR ; 32
	tilecoll FLOOR, WALL, FLOOR, WALL ; 33
	tilecoll FLOOR, FLOOR, WALL, WALL ; 34
	tilecoll WALL, WALL, FLOOR, FLOOR ; 35
	tilecoll WALL, WALL, FLOOR, FLOOR ; 36
	tilecoll FLOOR, WALL, FLOOR, WALL ; 37
	tilecoll FLOOR, WALL, FLOOR, WALL ; 38
	tilecoll WALL, WALL, FLOOR, FLOOR ; 39
	tilecoll FLOOR, WALL, WALL, WALL ; 3a
	tilecoll WALL, WALL, FLOOR, WALL ; 3b
	tilecoll WALL, WALL, WALL, FLOOR ; 3c
	tilecoll WALL, WALL, FLOOR, WALL ; 3d
	tilecoll WALL, FLOOR, WALL, WALL ; 3e
	tilecoll FLOOR, COUNTER, COUNTER, COUNTER ; 3f
	tilecoll WALL, FLOOR, WALL, FLOOR ; 40
	tilecoll FLOOR, WALL, FLOOR, WALL ; 41
	tilecoll WALL, WALL, WALL, WALL ; 42
	tilecoll WALL, WALL, WALL, WALL ; 43
	tilecoll WALL, WALL, WALL, FLOOR ; 44
	tilecoll WALL, WALL, FLOOR, FLOOR ; 45
	tilecoll WALL, WALL, FLOOR, WALL ; 46
	tilecoll WALL, FLOOR, WALL, WALL ; 47
	tilecoll WALL, FLOOR, WALL, FLOOR ; 48
	tilecoll WALL, WALL, WALL, WALL ; 49
	tilecoll FLOOR, WALL, FLOOR, WALL ; 4a
	tilecoll WALL, WALL, WALL, WALL ; 4b
	tilecoll WALL, FLOOR, WALL, WALL ; 4c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 4d
	tilecoll FLOOR, WALL, WALL, WALL ; 4e
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 4f
	tilecoll WALL, FLOOR, WALL, FLOOR ; 50
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 51
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 52
	tilecoll FLOOR, WALL, WALL, WALL ; 53
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 54
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 55
	tilecoll WALL, WALL, FLOOR, FLOOR ; 56
	tilecoll WALL, WALL, WALL, WALL ; 57
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 58
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 59
	tilecoll FLOOR, LADDER, FLOOR, FLOOR ; 5a
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 5b
	tilecoll WALL, FLOOR, WALL, FLOOR ; 5c
	tilecoll FLOOR, WALL, FLOOR, WALL ; 5d
	tilecoll WALL, WALL, LADDER, FLOOR ; 5e
	tilecoll WALL, FLOOR, WALL, FLOOR ; 5f
	tilecoll WALL, WALL, WALL, WALL ; 60
	tilecoll WALL, WALL, FLOOR, FLOOR ; 61
	tilecoll WALL, WALL, FLOOR, FLOOR ; 62
	tilecoll WALL, FLOOR, WALL, FLOOR ; 63
	tilecoll FLOOR, FLOOR, WALL, WALL ; 64
	tilecoll FLOOR, FLOOR, WALL, WALL ; 65
	tilecoll FLOOR, FLOOR, WALL, WALL ; 66
	tilecoll FLOOR, WALL, FLOOR, WALL ; 67
	tilecoll WALL, WALL, WALL, WALL ; 68
	tilecoll WALL, WALL, WALL, WALL ; 69
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 6a
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 6b
	tilecoll WALL, WALL, WALL, WALL ; 6c
	tilecoll WALL, WALL, WALL, WALL ; 6d
	tilecoll FLOOR, WALL, FLOOR, WALL ; 6e
	tilecoll FLOOR, WALL, FLOOR, WALL ; 6f
	tilecoll WALL, WALL, WALL, WALL ; 70
	tilecoll WALL, WALL, WALL, WALL ; 71
	tilecoll WALL, WALL, LADDER, FLOOR ; 72
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 73
	tilecoll WALL, WALL, WALL, FLOOR ; 74
	tilecoll FLOOR, FLOOR, WALL, WALL ; 75
	tilecoll WALL, WALL, FLOOR, FLOOR ; 76
	tilecoll FLOOR, FLOOR, WALL, WALL ; 77
	tilecoll WALL, WALL, FLOOR, FLOOR ; 78
	tilecoll FLOOR, WALL, FLOOR, WALL ; 79
